/**

 * Auto-generated types based on API schema

 * Generated by axiosflow

 * @generated

 * @timestamp 2024-12-26T10:51:07.424Z

 */


export interface User {
    id: number;
    name: string;
}


export interface UserRequest {
    name: string;
}